apiVersion: apps/v1
kind: Deployment
metadata:
  name: polling-app-server
  labels:
    app: polling-app-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: polling-app-server
  template:
    metadata:
      labels:
        app: polling-app-server
    spec:
      containers:
      - name: polling-app-server
        image: saihari1/poll:pollb  # Updated image name to "saihari1/poll:pollb"
        imagePullPolicy: IfNotPresent
        ports:
          - name: backend  # Name for the port
            containerPort: 8090  # The backend container listens on port 8090
        resources:
          limits:
            cpu: 0.2
            memory: "200Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: polling-app-server
  labels:
    app: polling-app-server
spec:
  type: NodePort  # Exposing the service on each node's port
  selector:
    app: polling-app-server
  ports:
    - name: backend  # The name of the service port (for clarity)
      port: 8090      # Exposing the service externally on port 8090
      targetPort: 8090  # Forwarding the traffic to the backend container's port 8090
