apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "skillzverse.fullname" . }}-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ include "skillzverse.fullname" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "skillzverse.fullname" . }}-frontend
    spec:
{{- if .Values.imagePullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecretName }}
{{- end }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image }}"
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
