name: Java CI with Maven and Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build Backend with Maven
      working-directory: polling-app-server
      run: mvn -B package --file pom.xml

    - name: Build Backend Docker Image
      working-directory: polling-app-server
      run: |
        docker build -t saihari1/hari-backend:latestb .

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install npm Dependencies
      working-directory: polling-app-client
      run: npm install

    - name: Build Frontend
      working-directory: polling-app-client
      run: npm run build

    - name: Build Frontend Docker Image
      working-directory: polling-app-client
      run: |
        docker build -t saihari1/hari-frontend:latestf .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Push Backend Docker Image
      run: |
        docker push saihari1/hari-backend:latestb

    - name: Push Frontend Docker Image
      run: |
        docker push saihari1/hari-frontend:latestf
